#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

pnpm commitlint --edit ${1}

if ! git diff --quiet HEAD $REF -- frontend; then
  echo Changes found in frontend folder

  cd frontend
  pnpm run-p lint ts format:check
fi