#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

if ! git diff --quiet HEAD $REF -- frontend; then
  echo Changes found in frontend folder

  cd frontend
  pnpm prettier
  pnpm lint --fix
fi

git add .
