function Head() {
  return (
    <>
      <title>DALL-E 2.0</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
    </>
  );
}

export default Head;
