import { getAllPosts } from "@api/client";
// import Search from "@components/Search";

async function Page() {
  const posts = await getAllPosts({
    page: 1,
    pageSize: 25,
  });

  return (
    <section className="mx-auto max-w-7xl">
      <div>
        <h1 className="text-3xl font-extrabold text-[#222328]">
          The Community Showcase
        </h1>
        <p className="mt-2 max-w-lg text-base text-[#666e75]">
          Browse through a collection of imaginative and visually stunning
          images generated by DALL-E AI
        </p>
      </div>

      <div className="mt-16">
        {/* <FormField
          labelName="Search posts"
          type="text"
          name="text"
          placeholder="Search something..."
          value=""
        /> */}
      </div>

      <div className="mt-10">
        {posts.data.map(
          ({ id, createdAt, updatedAt, code, language, theme }) => (
            <div key={id}>
              <time>{createdAt}</time>
              <p>{code}</p>
            </div>
          )
        )}
        {/* {false ? (
          <div className="justify-cetner flex items-center">
            <Loader />
          </div>
        ) : (
          <Search />
        )} */}
      </div>
    </section>
  );
}

export default Page;
