import Loader from "@components/Loader";
import Search from "@components/Search";

function Page() {
  return (
    <section className="mx-auto max-w-7xl">
      <div>
        <h1 className="text-3xl font-extrabold text-[#222328]">
          The Community Showcase
        </h1>
        <p className="mt-2 max-w-lg text-base text-[#666e75]">
          Browse through a collection of imaginative and visually stunning
          images generated by DALL-E AI
        </p>
      </div>

      <div className="mt-16">
        {/* <FormField
          labelName="Search posts"
          type="text"
          name="text"
          placeholder="Search something..."
          value=""
        /> */}
      </div>

      <div className="mt-10">
        {false ? (
          <div className="justify-cetner flex items-center">
            <Loader />
          </div>
        ) : (
          <Search />
        )}
      </div>
    </section>
  );
}

export default Page;
